// Generates src/tables.rs (type chart, species, moves, abilities, items, conditions and
// their event-handler tables), oracle/pool.json and oracle/coverage.json from Pokémon
// Showdown's Champions data.
'use strict';
const fs = require('fs');
const path = require('path');
const L = require('./lib.js');
const { dex } = L;

const TYPES = [
	'Normal', 'Fighting', 'Flying', 'Poison', 'Ground', 'Rock', 'Bug', 'Ghost', 'Steel',
	'Fire', 'Water', 'Grass', 'Electric', 'Psychic', 'Ice', 'Dragon', 'Dark', 'Fairy',
];
for (const t of dex.types.names()) if (!TYPES.includes(t) && t !== 'Stellar') throw new Error('unknown type ' + t);

const rs = s => JSON.stringify(s);
// Showdown applies a stat-change table in the order its keys are written, and a
// couple of moves (Shell Smash, Shift Gear) do not list them atk..evasion. Those
// orders are collected here; index 0 is the canonical order.
const boostOrders = [L.BOOST_IDS.map((_, i) => i).join(', ')];
const boostOrder = b => {
	if (!b) return 0;
	const keys = Object.keys(b).map(k => L.BOOST_IDS.indexOf(k));
	if (keys.every((k, i) => i === 0 || keys[i - 1] < k)) return 0;
	const rest = L.BOOST_IDS.map((_, i) => i).filter(i => !keys.includes(i));
	const lit = [...keys, ...rest].join(', ');
	if (!boostOrders.includes(lit)) boostOrders.push(lit);
	return boostOrders.indexOf(lit);
};
const boostsLit = (b, allowOrder) => {
	if (!b) return 'None';
	for (const k in b) if (!L.BOOST_IDS.includes(k)) throw new Error('bad boost ' + k);
	if (!allowOrder && boostOrder(b) !== 0) throw new Error('boost keys out of canonical order: ' + Object.keys(b));
	return `Some([${L.BOOST_IDS.map(k => b[k] || 0).join(', ')}])`;
};
const volName = id => { id = L.PS.toID(id); return id[0].toUpperCase() + id.slice(1); };
// A condition named by a move, as a literal of the enum for its class.
const condLit = (v, cls, enumName) => {
	if (!v) return 'None';
	if (L.condClass(v) !== cls) throw new Error(`${v} is not a modelled ${cls} condition`);
	return `Some(${enumName}::${volName(v)})`;
};
const volLit = v => condLit(v, 'volatile', 'VolKind');
const fieldLit = (v, cls, enumName) => (v ? condLit(v, cls, enumName).slice(5, -1) : `${enumName}::None`);
const statusLit = s => (s ? 'Status::' + s[0].toUpperCase() + s.slice(1) : 'Status::None');
const frac = f => (f ? `(${f[0]}, ${f[1]})` : '(0, 0)');
const statIdx = s => (s ? L.STAT_IDS.indexOf(s) : 0);
const selfSwitchLit = v => {
	if (!v) return 'No';
	if (v === true) return 'Yes';
	if (v === 'copyvolatile') return 'CopyVolatile';
	if (v === 'shedtail') return 'ShedTail';
	throw new Error('selfSwitch: ' + v);
};
const FLAGS = {
	protect: 'F_PROTECT', powder: 'F_POWDER', defrost: 'F_DEFROST', contact: 'F_CONTACT', sound: 'F_SOUND', heal: 'F_HEAL',
	punch: 'F_PUNCH', bite: 'F_BITE', bullet: 'F_BULLET', pulse: 'F_PULSE', slicing: 'F_SLICING', wind: 'F_WIND',
	dance: 'F_DANCE', reflectable: 'F_REFLECTABLE', bypasssub: 'F_BYPASSSUB', mirror: 'F_MIRROR', snatch: 'F_SNATCH',
	charge: 'F_CHARGE', recharge: 'F_RECHARGE', futuremove: 'F_FUTUREMOVE', metronome: 'F_METRONOME',
	noparentalbond: 'F_NOPARENTALBOND', failcopycat: 'F_FAILCOPYCAT', mustpressure: 'F_MUSTPRESSURE', gravity: 'F_GRAVITY',
	nonsky: 'F_NONSKY', minimize: 'F_MINIMIZE', failencore: 'F_FAILENCORE', nosleeptalk: 'F_NOSLEEPTALK',
	failinstruct: 'F_FAILINSTRUCT', failmimic: 'F_FAILMIMIC', cantusetwice: 'F_CANTUSETWICE', noassist: 'F_NOASSIST',
	failmefirst: 'F_FAILMEFIRST',
};
// Flags with no effect on a battle's outcome in this format.
const IGNORED_FLAGS = new Set(['allyanim', 'distance', 'nosketch', 'pledgecombo']);
const TARGETS = {
	normal: 'Normal', any: 'Any', adjacentFoe: 'AdjacentFoe', allAdjacentFoes: 'AllAdjacentFoes', allAdjacent: 'AllAdjacent',
	self: 'User', adjacentAlly: 'AdjacentAlly', adjacentAllyOrSelf: 'AdjacentAllyOrSelf', allies: 'Allies',
	randomNormal: 'RandomNormal', all: 'All', allySide: 'AllySide', foeSide: 'FoeSide', allyTeam: 'AllyTeam', scripted: 'Scripted',
};

let out = '// @generated by oracle/gen_data.js from Pokémon Showdown data. Do not edit by hand.\n';
out += '#![allow(clippy::all)]\n';
out += 'use crate::data::*;\n\n';

// ---- type chart -----------------------------------------------------------
out += '/// `TYPE_CHART[attacking][defending]`: 0 neutral, 1 super effective, 2 resisted, 3 immune.\n';
out += `pub static TYPE_CHART: [[u8; ${TYPES.length}]; ${TYPES.length}] = [\n`;
for (const atk of TYPES) {
	out += '    [' + TYPES.map(def => dex.types.get(def).damageTaken[atk] || 0).join(', ') + `], // ${atk}\n`;
}
out += '];\n\n';
const IMM = ['brn', 'par', 'psn', 'slp', 'frz', 'powder', 'trapped', 'prankster', 'sandstorm'];
out += '/// `STATUS_IMMUNE[kind][type]` for kind = brn, par, psn (also tox), slp, frz, powder, trapped, prankster, sandstorm.\n';
out += `pub static STATUS_IMMUNE: [[bool; ${TYPES.length}]; ${IMM.length}] = [\n`;
for (const k of IMM) out += '    [' + TYPES.map(t => dex.types.get(t).damageTaken[k] === 3).join(', ') + `], // ${k}\n`;
out += '];\n\n';

// ---- species ----------------------------------------------------------------
const abilities = L.tableAbilities();
const abilityIndex = name => {
	const i = abilities.findIndex(a => a.id === L.PS.toID(name));
	if (i < 0) throw new Error('ability not in table: ' + name);
	return i;
};
const species = L.tableSpecies();
const speciesIndex = name => {
	const i = species.findIndex(s => s.id === L.PS.toID(name));
	if (i < 0) throw new Error('species not in table: ' + name);
	return i;
};
out += `pub static SPECIES: [SpeciesData; ${species.length}] = [\n`;
for (const s of species) {
	const t = s.types.map(x => 'Type::' + x);
	if (t.length === 1) t.push('Type::None');
	const b = s.baseStats;
	const gender = s.gender ? `Some(Gender::${s.gender})` : 'None';
	out += `    SpeciesData { id: ${rs(s.id)}, name: ${rs(s.name)}, base_species: ${rs(L.PS.toID(s.baseSpecies))}, types: [${t.join(', ')}], ` +
		`base: [${L.STAT_IDS.map(k => b[k]).join(', ')}], gender: ${gender}, ability0: ${abilityIndex(s.abilities['0'])}, weight_hg: ${s.weighthg}, illegal: ${s.tier === 'Illegal'} },\n`;
}
out += '];\n\n';

// ---- moves --------------------------------------------------------------------
const moves = L.tableMoves();
let secDefs = '';
let moveRows = '';
let mvConsts = '';
const report = { supported: [], unsupported: {} };
const evMask = evs => {
	let mask = 0n;
	for (const ev of evs) {
		if (!L.EVENTS.includes(ev)) throw new Error(`no Ev variant for move callback ${ev} (add it to src/data.rs)`);
		mask |= 1n << BigInt(L.EVENTS.indexOf(ev));
	}
	return `0x${mask.toString(16)}`;
};
moves.forEach((m, index) => {
	const why = L.unsupportedReasons(m);
	const supported = why.length === 0;
	if (supported) report.supported.push(m.id); else report.unsupported[m.id] = why;
	const pp = m.noPPBoosts ? m.pp : (m.pp / 5 + 1) * 4;
	if (!Number.isInteger(pp) || pp > 255) throw new Error(`bad pp for ${m.id}: ${pp}`);
	for (const f in m.flags) if (!FLAGS[f] && !IGNORED_FLAGS.has(f)) throw new Error(`move ${m.id}: unknown flag ${f}`);
	const flags = Object.keys(FLAGS).filter(f => m.flags[f]).map(f => FLAGS[f]).join(' | ') || '0';
	let secName = '&[]';
	let self = null, selfChance = 0, multihit = '(0, 0)';
	// Everything below is only filled in for modelled moves, so that unmodelled
	// ones cannot name conditions the engine has no variant for.
	const d = supported ? m : {};
	if (supported) {
		if (m.secondaries && m.secondaries.length) {
			secName = `SEC_${m.id.toUpperCase()}`;
			const rows = m.secondaries.map(s => `Secondary { chance: ${s.chance === undefined ? 0 : s.chance}, status: ${statusLit(s.status)}, ` +
				`boosts: ${boostsLit(s.boosts)}, volatile: ${volLit(s.volatileStatus)}, self_boosts: ${boostsLit(s.self && s.self.boosts)}, on_hit: ${!!s.onHit} }`);
			secDefs += `static ${secName}: [Secondary; ${rows.length}] = [${rows.join(', ')}];\n`;
			secName = '&' + secName;
		}
		if (m.self) { self = m.self.boosts; selfChance = m.self.chance === undefined ? 0 : m.self.chance; }
		if (m.multihit) multihit = Array.isArray(m.multihit) ? `(${m.multihit[0]}, ${m.multihit[1]})` : `(${m.multihit}, ${m.multihit})`;
	}
	const type = m.type === '???' ? 'Type::Typeless' : 'Type::' + m.type;
	const target = TARGETS[m.target];
	if (!target) throw new Error(`unknown target ${m.target} for ${m.id}`);
	mvConsts += `    pub const ${m.id.toUpperCase()}: u16 = ${index};\n`;
	moveRows += `    MoveData { id: ${rs(m.id)}, name: ${rs(m.name)}, typ: ${type}, category: Category::${m.category}, ` +
		`base_power: ${m.basePower}, accuracy: ${m.accuracy === true ? 0 : m.accuracy}, pp: ${pp}, base_pp: ${m.pp}, priority: ${m.priority}, ` +
		`target: Target::${target}, crit_ratio: ${m.critRatio || 0}, will_crit: ${!!m.willCrit}, flags: ${flags}, ` +
		`boosts: ${boostsLit(d.boosts, true)}, boost_order: ${boostOrder(d.boosts)}, status: ${statusLit(d.status)}, ` +
		`volatile: ${volLit(d.volatileStatus)}, self_volatile: ${volLit(d.self && d.self.volatileStatus)}, ` +
		`side_condition: ${condLit(d.sideCondition, 'side', 'SideCond')}, slot_condition: ${condLit(d.slotCondition, 'slot', 'SlotCond')}, ` +
		`pseudo_weather: ${condLit(d.pseudoWeather, 'pseudo', 'Pseudo')}, weather: ${fieldLit(d.weather, 'weather', 'Weather')}, ` +
		`terrain: ${fieldLit(d.terrain, 'terrain', 'Terrain')}, ` +
		`self_boosts: ${boostsLit(self)}, self_chance: ${selfChance}, self_on_hit: ${!!(d.self && d.self.onHit)}, secondaries: ${secName}, ` +
		`drain: ${frac(d.drain)}, recoil: ${frac(d.recoil)}, heal: ${frac(d.heal)}, multihit: ${multihit}, ` +
		`off_stat: ${statIdx(m.overrideOffensiveStat)}, def_stat: ${statIdx(m.overrideDefensiveStat)}, ` +
		`off_from_target: ${m.overrideOffensivePokemon === 'target'}, ignore_defensive: ${!!m.ignoreDefensive}, ` +
		`ignore_evasion: ${!!m.ignoreEvasion}, thaws_target: ${!!m.thawsTarget}, ignore_immunity: ${m.ignoreImmunity === true}, ` +
		`stalling_move: ${!!m.stallingMove}, struggle_recoil: ${!!m.struggleRecoil}, breaks_protect: ${!!m.breaksProtect}, ` +
		`fixed_damage: ${d.damage === 'level' ? 'FixedDamage::Level' : 'FixedDamage::No'}, ` +
		`selfdestruct: ${d.selfdestruct === 'always' ? 'SelfDestruct::Always' : d.selfdestruct === 'ifHit' ? 'SelfDestruct::IfHit' : 'SelfDestruct::No'}, ` +
		`self_boost: ${boostsLit(d.selfBoost && d.selfBoost.boosts, true)}, self_boost_order: ${boostOrder(d.selfBoost && d.selfBoost.boosts)}, ` +
		`mind_blown_recoil: ${!!d.mindBlownRecoil}, ` +
		`tracks_target: ${!!m.tracksTarget}, smart_target: ${!!m.smartTarget}, calls_move: ${!!m.callsMove}, has_crash_damage: ${!!m.hasCrashDamage}, sheer_force_boost: ${!!m.hasSheerForceBoost}, self_switch: SelfSwitch::${selfSwitchLit(m.selfSwitch)}, force_switch: ${!!m.forceSwitch}, sleep_usable: ${!!m.sleepUsable}, multiaccuracy: ${!!d.multiaccuracy}, ` +
		`ohko: ${d.ohko === true ? 'Ohko::Yes' : d.ohko === 'Ice' ? 'Ohko::Ice' : d.ohko ? (() => { throw new Error('ohko ' + d.ohko); })() : 'Ohko::No'}, ` +
		`events: ${supported ? evMask(L.moveCallbacks(m)) : '0'}, supported: ${supported} },\n`;
});
for (const id of L.HAND_MOVES) if (!moves.some(m => m.id === id)) throw new Error('hand-written move not in table: ' + id);

// ---- event handlers of conditions, abilities and items ----------------------------
let cbDefs = '';
/** Emits the callback table of one effect; returns [slice expression, events bit set literal]. */
function cbTable(name, effect, what, cls) {
	const cbs = L.callbacks(effect, cls);
	const unknown = cbs.filter(c => c.unknown).map(c => c.key);
	if (unknown.length) throw new Error(`${what} ${effect.id}: no Ev variant for ${unknown.join(', ')} (add it to src/data.rs)`);
	if (!cbs.length) return ['&[]', '0', '0'];
	let mask = 0n, maskPre = 0n;
	const rows = cbs.map(c => {
		if (c.pre === 'On') mask |= 1n << BigInt(L.EVENTS.indexOf(c.ev));
		else maskPre |= 1n << BigInt(L.EVENTS.indexOf(c.ev));
		const prio = c.priority * 10;
		if (!Number.isInteger(prio) || !Number.isInteger(c.order) || !Number.isInteger(c.subOrder)) throw new Error(`${effect.id}.${c.key}: odd ordering values`);
		return `CbInfo { ev: Ev::${c.ev}, pre: Pre::${c.pre}, order: ${c.order}, priority: ${prio}, sub_order: ${c.subOrder}, kind: CbKind::${c.kind} }`;
	});
	cbDefs += `static ${name}: [CbInfo; ${rows.length}] = [\n${rows.map(r => '    ' + r + ',\n').join('')}];\n`;
	return ['&' + name, `0x${mask.toString(16)}`, `0x${maskPre.toString(16)}`];
}

const BLANK_COND = '    CondData { id: "", duration: 0, affects_fainted: false, no_copy: false, duration_cb: false, cbs: &[], events: 0, events_pre: 0 },\n';
/** The `CondData` rows of one class of conditions. */
function condRows(ids, cls, prefix) {
	let rows = '';
	for (const id of ids) {
		const c = dex.conditions.get(id);
		if (!c.exists && !L.BARE_VOLATILES.has(id)) throw new Error('unknown condition ' + id);
		const [cbs, mask, maskPre] = cbTable(`CB_${prefix}_${id.toUpperCase()}`, c, 'condition', cls);
		rows += `    CondData { id: ${rs(id)}, duration: ${c.duration || 0}, affects_fainted: ${!!c.affectsFainted}, no_copy: ${!!c.noCopy}, ` +
			`duration_cb: ${!!c.durationCallback}, cbs: ${cbs}, events: ${mask}, events_pre: ${maskPre} },\n`;
	}
	return rows;
}
const volRows = condRows(L.VOLATILES, 'volatile', 'VOL');
const statusRows = BLANK_COND + condRows(L.STATUSES, 'status', 'STATUS');
const sideRows = condRows(L.SIDE_CONDS, 'side', 'SIDE');
const slotRows = condRows(L.SLOT_CONDS, 'slot', 'SLOT');
const pseudoRows = condRows(L.PSEUDO_WEATHERS, 'pseudo', 'PSEUDO');
const weatherRows = BLANK_COND + condRows(L.WEATHERS, 'weather', 'WEATHER');
const terrainRows = BLANK_COND + condRows(L.TERRAINS, 'terrain', 'TERRAIN');

// Abilities
const AFLAGS = {
	breakable: 'AF_BREAKABLE', cantsuppress: 'AF_CANTSUPPRESS', notransform: 'AF_NOTRANSFORM', failskillswap: 'AF_FAILSKILLSWAP',
	failroleplay: 'AF_FAILROLEPLAY', noreceiver: 'AF_NORECEIVER', noentrain: 'AF_NOENTRAIN', notrace: 'AF_NOTRACE',
};
let abRows = '', abConsts = '';
abilities.forEach((a, i) => {
	const supported = L.SUPPORTED_ABILITIES.has(a.id);
	for (const f in a.flags) if (!AFLAGS[f]) throw new Error(`ability ${a.id}: unknown flag ${f}`);
	const flags = Object.keys(a.flags).map(f => AFLAGS[f]).join(' | ') || '0';
	const [cbs, mask, maskPre] = supported ? cbTable(`CB_AB_${a.id.toUpperCase()}`, a, 'ability', 'ability') : ['&[]', '0', '0'];
	abConsts += `    pub const ${a.id.toUpperCase()}: u16 = ${i};\n`;
	abRows += `    AbilityData { id: ${rs(a.id)}, name: ${rs(a.name)}, flags: ${flags}, supported: ${supported}, cbs: ${cbs}, events: ${mask}, events_pre: ${maskPre} },\n`;
});
for (const id of L.SUPPORTED_ABILITIES) if (!abilities.some(a => a.id === id)) throw new Error('supported ability not in table: ' + id);

// Items
const items = L.tableItems();
const NO_FLING = 'Fling { power: 0, status: Status::None, flinch: false, effect: false }';
/** What an item does when thrown with Fling. Berries are eaten by the target instead. */
function flingLit(item) {
	const f = item.fling;
	if (!f) return NO_FLING;
	for (const k in f) if (!['basePower', 'status', 'volatileStatus', 'effect'].includes(k)) throw new Error(`item ${item.id}: fling.${k}`);
	if (f.volatileStatus && f.volatileStatus !== 'flinch') throw new Error(`item ${item.id}: fling volatile ${f.volatileStatus}`);
	if (f.effect && !['mentalherb', 'whiteherb'].includes(item.id)) throw new Error(`item ${item.id}: fling effect has no body`);
	return `Fling { power: ${f.basePower}, status: ${statusLit(f.status)}, flinch: ${!!f.volatileStatus}, effect: ${!!f.effect} }`;
}
let itRows = `    ItemData { id: "", name: "", flags: 0, supported: true, cbs: &[], events: 0, events_pre: 0, mega: &[], boosts: None, fling: ${NO_FLING} },\n`;
let megaDefs = '';
let itConsts = '    pub const NONE: u16 = 0;\n';
items.forEach((item, i) => {
	const supported = L.SUPPORTED_ITEMS.has(item.id);
	const fl = [];
	if (item.isBerry) fl.push('IF_BERRY');
	if (item.isGem) fl.push('IF_GEM');
	if (item.isChoice) fl.push('IF_CHOICE');
	if (item.ignoreKlutz) fl.push('IF_IGNORE_KLUTZ');
	const [cbs, mask, maskPre] = supported ? cbTable(`CB_IT_${item.id.toUpperCase()}`, item, 'item', 'item') : ['&[]', '0', '0'];
	let mega = '&[]';
	if (item.megaStone) {
		// Who the stone cannot be taken from. Two rules exist; refuse to guess at a third.
		const rule = (item.onTakeItem || '').toString().replace(/\s+/g, ' ');
		if (rule.includes('!item.megaStone[source.baseSpecies.name] && !Object.values(item.megaStone).includes(source.baseSpecies.name)')) {
			fl.push('IF_MEGA_BY_FORME');
		} else if (!rule.includes('return !item.megaStone?.[source.baseSpecies.baseSpecies];')) {
			throw new Error(`item ${item.id}: unrecognised onTakeItem`);
		}
		// (species that can use the stone, the Mega it becomes)
		const pairs = Object.entries(item.megaStone).map(([from, to]) => `(${speciesIndex(from)}, ${speciesIndex(to)})`);
		megaDefs += `static MEGA_${item.id.toUpperCase()}: [(u16, u16); ${pairs.length}] = [${pairs.join(', ')}];\n`;
		mega = `&MEGA_${item.id.toUpperCase()}`;
	}
	itConsts += `    pub const ${item.id.toUpperCase()}: u16 = ${i + 1};\n`;
	itRows += `    ItemData { id: ${rs(item.id)}, name: ${rs(item.name)}, flags: ${fl.join(' | ') || '0'}, supported: ${supported}, cbs: ${cbs}, events: ${mask}, events_pre: ${maskPre}, mega: ${mega}, boosts: ${boostsLit(item.boosts)}, fling: ${flingLit(item)} },\n`;
});
for (const id of L.SUPPORTED_ITEMS) if (id && !items.some(a => a.id === id)) throw new Error('supported item not in table: ' + id);

/** A Rust enum with one variant per condition id (plus `None` first when `withNone`). */
function condEnum(name, doc, ids, table, withNone) {
	let e = `/// ${doc}\n#[derive(Clone, Copy, PartialEq, Eq, Debug)]\n#[repr(u8)]\npub enum ${name} {\n`;
	if (withNone) e += '    None,\n';
	e += ids.map(id => `    ${volName(id)},\n`).join('');
	e += `}\n\nimpl ${name} {\n    pub fn id(self) -> &'static str {\n        ${table}[self as usize].id\n    }\n` +
		`    pub fn data(self) -> &'static CondData {\n        &${table}[self as usize]\n    }\n` +
		`    pub const FIRST: ${name} = ${name}::${withNone ? 'None' : volName(ids[0])};\n` +
		`    pub const ALL: [${name}; ${ids.length + (withNone ? 1 : 0)}] = [${(withNone ? ['None'] : []).concat(ids.map(volName)).map(v => `${name}::${v}`).join(', ')}];\n` +
		`    /// The condition with this id, if the engine models it.\n` +
		`    pub fn named(id: &str) -> Option<${name}> {\n        ${name}::ALL.iter().copied().find(|k| !id.is_empty() && k.id() == id)\n    }\n}\n\n`;
	return e;
}
for (const [name, ids] of [['side', L.SIDE_CONDS], ['slot', L.SLOT_CONDS], ['pseudo', L.PSEUDO_WEATHERS]]) {
	if (!ids.length) throw new Error(`the ${name} condition list must not be empty`);
}
out += '/// Orders in which a stat-change table is applied; `MoveData::boost_order` indexes this.\n';
out += `pub static BOOST_ORDERS: [[u8; 7]; ${boostOrders.length}] = [${boostOrders.map(o => `[${o}]`).join(', ')}];\n\n`;
out += condEnum('VolKind', 'Volatile conditions the engine models (conditions that sit on a Pokémon), in the order of `VOL_CONDS`.', L.VOLATILES, 'VOL_CONDS', false);
out += condEnum('SideCond', 'Conditions that sit on one side of the field, in the order of `SIDE_CONDS`.', L.SIDE_CONDS, 'SIDE_CONDS', false);
out += condEnum('SlotCond', 'Conditions that sit on one active position of a side, in the order of `SLOT_CONDS`.', L.SLOT_CONDS, 'SLOT_CONDS', false);
out += condEnum('Pseudo', 'Pseudo-weathers (conditions on the whole field), in the order of `PSEUDO_CONDS`.', L.PSEUDO_WEATHERS, 'PSEUDO_CONDS', false);
out += condEnum('Weather', 'Weather; `WEATHER_CONDS` is indexed by it.', L.WEATHERS, 'WEATHER_CONDS', true);
out += condEnum('Terrain', 'Terrain; `TERRAIN_CONDS` is indexed by it.', L.TERRAINS, 'TERRAIN_CONDS', true);
out += `/// Number of \`VolKind\` variants.\npub const N_VOLATILES: usize = ${L.VOLATILES.length};\n`;
out += `pub const N_SIDE_CONDS: usize = ${L.SIDE_CONDS.length};\npub const N_SLOT_CONDS: usize = ${L.SLOT_CONDS.length};\npub const N_PSEUDO: usize = ${L.PSEUDO_WEATHERS.length};\n\n`;
out += secDefs + '\n';
out += `/// Move indices into \`MOVES\`.\npub mod mv {\n${mvConsts}}\n\n`;
out += `pub static MOVES: [MoveData; ${moves.length}] = [\n${moveRows}];\n\n`;
out += cbDefs + '\n';
out += `pub static VOL_CONDS: [CondData; ${L.VOLATILES.length}] = [\n${volRows}];\n\n`;
out += '/// Indexed by `Status as usize`.\n';
out += `pub static STATUS_CONDS: [CondData; ${L.STATUSES.length + 1}] = [\n${statusRows}];\n\n`;
out += `pub static SIDE_CONDS: [CondData; ${L.SIDE_CONDS.length}] = [\n${sideRows}];\n\n`;
out += `pub static SLOT_CONDS: [CondData; ${L.SLOT_CONDS.length}] = [\n${slotRows}];\n\n`;
out += `pub static PSEUDO_CONDS: [CondData; ${L.PSEUDO_WEATHERS.length}] = [\n${pseudoRows}];\n\n`;
out += `pub static WEATHER_CONDS: [CondData; ${L.WEATHERS.length + 1}] = [\n${weatherRows}];\n\n`;
out += `pub static TERRAIN_CONDS: [CondData; ${L.TERRAINS.length + 1}] = [\n${terrainRows}];\n\n`;
out += `/// Ability indices into \`ABILITIES\`.\npub mod ab {\n${abConsts}}\n\n`;
out += `pub static ABILITIES: [AbilityData; ${abilities.length}] = [\n${abRows}];\n\n`;
out += `/// Item indices into \`ITEMS\`.\npub mod it {\n${itConsts}}\n\n`;
out += megaDefs + '\n';
out += `pub static ITEMS: [ItemData; ${items.length + 1}] = [\n${itRows}];\n`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'tables.rs'), out);

// ---- pool for the fuzzer --------------------------------------------------------
const supportedSet = new Set(report.supported);
const pool = {
	species: [],
	natures: dex.natures.all().map(n => n.name),
	abilities: [...L.SUPPORTED_ABILITIES].filter(a => a !== 'noability').sort(),
	// Ordinary held items; Mega Stones are listed separately (`megastones`, and per species).
	items: [...L.SUPPORTED_ITEMS].filter(id => id && !dex.items.get(id).megaStone).sort(),
};
const learnable = new Set();
for (const s of L.legalSpecies()) {
	if (s.isMega || s.battleOnly) continue; // reached in battle, never brought
	const all = L.learnableMoves(s);
	for (const id of all) learnable.add(id);
	const ok = all.filter(id => supportedSet.has(id));
	const own = [...new Set(Object.values(s.abilities).map(a => L.PS.toID(a)))].filter(a => L.SUPPORTED_ABILITIES.has(a));
	// Mega Stones this species can use, where the Mega's ability is modelled.
	const megas = items.filter(i => i.megaStone && i.megaStone[s.name] &&
		L.SUPPORTED_ABILITIES.has(L.PS.toID(dex.species.get(i.megaStone[s.name]).abilities['0']))).map(i => i.id);
	// (Ditto learns one move, and is brought with just that.)
	const few = all.length < 4 && ok.length === all.length && ok.length > 0;
	if (ok.length >= 4 || few) pool.species.push({ id: s.id, moves: ok, abilities: own, gender: s.gender || '', megas });
}
pool.megastones = items.filter(i => i.megaStone).map(i => i.id);
fs.writeFileSync(path.join(__dirname, 'pool.json'), JSON.stringify(pool));

const learnOk = [...learnable].filter(id => supportedSet.has(id));
const tally = {};
for (const id of learnable) for (const w of report.unsupported[id] || []) tally[w] = (tally[w] || 0) + 1;
const legalAb = L.legalAbilities();
const heldItems = items.filter(i => !i.megaStone).map(i => i.id);
// Every Mega a stone leads to, and what it waits for if its ability is not modelled.
const megaList = [];
for (const item of items) {
	for (const to of Object.values(item.megaStone || {})) {
		const ability = L.PS.toID(dex.species.get(to).abilities['0']);
		megaList.push({ id: L.PS.toID(to), why: L.SUPPORTED_ABILITIES.has(ability) ? '' : `its ability ${ability} needs ${L.DEFERRED_ABILITIES[ability] || 'writing'}` });
	}
}
for (const kind of ['abilities', 'items']) {
	const supportedSet = kind === 'abilities' ? L.SUPPORTED_ABILITIES : L.SUPPORTED_ITEMS;
	for (const id in L.DORMANT_PARTS[kind]) if (!supportedSet.has(id)) throw new Error(`dormant ${kind} entry ${id} is not modelled`);
}
fs.writeFileSync(path.join(__dirname, 'coverage.json'), JSON.stringify({
	abilities: {
		legal: legalAb.length,
		modelled: legalAb.filter(a => L.SUPPORTED_ABILITIES.has(a)).length,
		not_modelled: Object.fromEntries(legalAb.filter(a => !L.SUPPORTED_ABILITIES.has(a)).map(a => [a, L.DEFERRED_ABILITIES[a] || 'not yet written'])),
		dormant_parts: L.DORMANT_PARTS.abilities,
	},
	items: {
		held_items: heldItems.length,
		modelled: heldItems.filter(i => L.SUPPORTED_ITEMS.has(i)).length,
		not_modelled: Object.fromEntries(heldItems.filter(i => !L.SUPPORTED_ITEMS.has(i)).map(i => [i, L.DEFERRED_ITEMS[i] || 'not yet written'])),
		mega_stones: items.filter(i => i.megaStone).length,
		megas: megaList.length,
		megas_modelled: megaList.filter(m => !m.why).length,
		megas_not_modelled: Object.fromEntries(megaList.filter(m => m.why).map(m => [m.id, m.why])),
		dormant_parts: L.DORMANT_PARTS.items,
	},
	learnable_moves: learnable.size,
	supported_learnable_moves: learnOk.length,
	supported: learnOk.sort(),
	unsupported: Object.fromEntries([...learnable].filter(id => !supportedSet.has(id)).sort().map(id => [id, report.unsupported[id]])),
	blocking_reasons: Object.fromEntries(Object.entries(tally).sort((a, b) => b[1] - a[1])),
}, null, 1));
console.log(`species ${species.length}, moves ${moves.length}; Champions-learnable moves ${learnable.size}, modelled ${learnOk.length}; ` +
	`abilities ${legalAb.filter(a => L.SUPPORTED_ABILITIES.has(a)).length}/${legalAb.length}; ` +
	`held items ${heldItems.filter(i => L.SUPPORTED_ITEMS.has(i)).length}/${heldItems.length}; fuzz pool species ${pool.species.length}`);
