// Generates src/tables.rs (type chart, species table, move table) and oracle/pool.json
// from Pokémon Showdown's Champions data.
'use strict';
const fs = require('fs');
const path = require('path');
const L = require('./lib.js');
const { dex } = L;

const TYPES = [
	'Normal', 'Fighting', 'Flying', 'Poison', 'Ground', 'Rock', 'Bug', 'Ghost', 'Steel',
	'Fire', 'Water', 'Grass', 'Electric', 'Psychic', 'Ice', 'Dragon', 'Dark', 'Fairy',
];
for (const t of dex.types.names()) if (!TYPES.includes(t) && t !== 'Stellar') throw new Error('unknown type ' + t);

const rs = s => JSON.stringify(s);
const boostsLit = b => {
	if (!b) return 'None';
	for (const k in b) if (!L.BOOST_IDS.includes(k)) throw new Error('bad boost ' + k);
	return `Some([${L.BOOST_IDS.map(k => b[k] || 0).join(', ')}])`;
};
const statusLit = s => (s ? 'Status::' + s[0].toUpperCase() + s.slice(1) : 'Status::None');
const frac = f => (f ? `(${f[0]}, ${f[1]})` : '(0, 0)');
const statIdx = s => (s ? L.STAT_IDS.indexOf(s) : 0);
const FLAGS = { protect: 'F_PROTECT', powder: 'F_POWDER', defrost: 'F_DEFROST', contact: 'F_CONTACT', sound: 'F_SOUND', heal: 'F_HEAL' };
const TARGETS = {
	normal: 'Normal', any: 'Any', adjacentFoe: 'AdjacentFoe', allAdjacentFoes: 'AllAdjacentFoes', allAdjacent: 'AllAdjacent',
	self: 'User', adjacentAlly: 'AdjacentAlly', adjacentAllyOrSelf: 'AdjacentAllyOrSelf', allies: 'Allies',
	randomNormal: 'RandomNormal', all: 'All', allySide: 'AllySide', foeSide: 'FoeSide', allyTeam: 'AllyTeam', scripted: 'Scripted',
};

let out = '// @generated by oracle/gen_data.js from Pokémon Showdown data. Do not edit by hand.\n';
out += '#![allow(clippy::all)]\n';
out += 'use crate::data::*;\n\n';

// ---- type chart -----------------------------------------------------------
out += '/// `TYPE_CHART[attacking][defending]`: 0 neutral, 1 super effective, 2 resisted, 3 immune.\n';
out += `pub static TYPE_CHART: [[u8; ${TYPES.length}]; ${TYPES.length}] = [\n`;
for (const atk of TYPES) {
	out += '    [' + TYPES.map(def => dex.types.get(def).damageTaken[atk] || 0).join(', ') + `], // ${atk}\n`;
}
out += '];\n\n';
const IMM = ['brn', 'par', 'psn', 'slp', 'frz', 'powder'];
out += '/// `STATUS_IMMUNE[kind][type]` for kind = brn, par, psn (also tox), slp, frz, powder.\n';
out += `pub static STATUS_IMMUNE: [[bool; ${TYPES.length}]; ${IMM.length}] = [\n`;
for (const k of IMM) out += '    [' + TYPES.map(t => dex.types.get(t).damageTaken[k] === 3).join(', ') + `], // ${k}\n`;
out += '];\n\n';

// ---- species ----------------------------------------------------------------
const species = L.tableSpecies();
out += `pub static SPECIES: [SpeciesData; ${species.length}] = [\n`;
for (const s of species) {
	const t = s.types.map(x => 'Type::' + x);
	if (t.length === 1) t.push('Type::None');
	const b = s.baseStats;
	out += `    SpeciesData { id: ${rs(s.id)}, name: ${rs(s.name)}, types: [${t.join(', ')}], base: [${L.STAT_IDS.map(k => b[k]).join(', ')}] },\n`;
}
out += '];\n\n';

// ---- moves --------------------------------------------------------------------
const moves = L.tableMoves();
let secDefs = '';
let moveRows = '';
const report = { supported: [], unsupported: {} };
for (const m of moves) {
	const why = L.unsupportedReasons(m);
	const supported = why.length === 0;
	if (supported) report.supported.push(m.id); else report.unsupported[m.id] = why;
	const pp = m.noPPBoosts ? m.pp : (m.pp / 5 + 1) * 4;
	if (!Number.isInteger(pp) || pp > 255) throw new Error(`bad pp for ${m.id}: ${pp}`);
	const flags = Object.keys(FLAGS).filter(f => m.flags[f]).map(f => FLAGS[f]).join(' | ') || '0';
	let secName = '&[]';
	let self = null, selfChance = 0, multihit = '(0, 0)';
	if (supported) {
		if (m.secondaries && m.secondaries.length) {
			secName = `SEC_${m.id.toUpperCase()}`;
			const rows = m.secondaries.map(s => `Secondary { chance: ${s.chance === undefined ? 0 : s.chance}, status: ${statusLit(s.status)}, ` +
				`boosts: ${boostsLit(s.boosts)}, flinch: ${s.volatileStatus === 'flinch'}, self_boosts: ${boostsLit(s.self && s.self.boosts)} }`);
			secDefs += `static ${secName}: [Secondary; ${rows.length}] = [${rows.join(', ')}];\n`;
			secName = '&' + secName;
		}
		if (m.self) { self = m.self.boosts; selfChance = m.self.chance === undefined ? 0 : m.self.chance; }
		if (m.multihit) multihit = Array.isArray(m.multihit) ? `(${m.multihit[0]}, ${m.multihit[1]})` : `(${m.multihit}, ${m.multihit})`;
	}
	const type = m.type === '???' ? 'Type::Typeless' : 'Type::' + m.type;
	const target = TARGETS[m.target];
	if (!target) throw new Error(`unknown target ${m.target} for ${m.id}`);
	moveRows += `    MoveData { id: ${rs(m.id)}, name: ${rs(m.name)}, typ: ${type}, category: Category::${m.category}, ` +
		`base_power: ${m.basePower}, accuracy: ${m.accuracy === true ? 0 : m.accuracy}, pp: ${pp}, priority: ${m.priority}, ` +
		`target: Target::${target}, crit_ratio: ${m.critRatio || 0}, will_crit: ${!!m.willCrit}, flags: ${flags}, ` +
		`boosts: ${supported ? boostsLit(m.boosts) : 'None'}, status: ${supported ? statusLit(m.status) : 'Status::None'}, ` +
		`self_boosts: ${boostsLit(self)}, self_chance: ${selfChance}, secondaries: ${secName}, ` +
		`drain: ${frac(supported && m.drain)}, recoil: ${frac(supported && m.recoil)}, heal: ${frac(supported && m.heal)}, multihit: ${multihit}, ` +
		`off_stat: ${statIdx(m.overrideOffensiveStat)}, def_stat: ${statIdx(m.overrideDefensiveStat)}, ` +
		`off_from_target: ${m.overrideOffensivePokemon === 'target'}, ignore_defensive: ${!!m.ignoreDefensive}, ` +
		`ignore_evasion: ${!!m.ignoreEvasion}, thaws_target: ${!!m.thawsTarget}, ignore_immunity: ${m.ignoreImmunity === true}, ` +
		`special: Special::${L.SPECIAL[m.id] || 'None'}, supported: ${supported} },\n`;
}
out += secDefs + '\n';
out += `pub static MOVES: [MoveData; ${moves.length}] = [\n${moveRows}];\n`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'tables.rs'), out);

// ---- pool for the fuzzer --------------------------------------------------------
const supportedSet = new Set(report.supported);
const pool = { species: [], natures: dex.natures.all().map(n => n.name) };
const learnable = new Set();
for (const s of L.legalSpecies()) {
	if (s.isMega || s.battleOnly) continue; // reached in battle, never brought
	const all = L.learnableMoves(s);
	for (const id of all) learnable.add(id);
	const ok = all.filter(id => supportedSet.has(id));
	if (ok.length >= 4) pool.species.push({ id: s.id, moves: ok });
}
fs.writeFileSync(path.join(__dirname, 'pool.json'), JSON.stringify(pool));

const learnOk = [...learnable].filter(id => supportedSet.has(id));
const tally = {};
for (const id of learnable) for (const w of report.unsupported[id] || []) tally[w] = (tally[w] || 0) + 1;
fs.writeFileSync(path.join(__dirname, 'coverage.json'), JSON.stringify({
	learnable_moves: learnable.size,
	supported_learnable_moves: learnOk.length,
	supported: learnOk.sort(),
	unsupported: Object.fromEntries([...learnable].filter(id => !supportedSet.has(id)).sort().map(id => [id, report.unsupported[id]])),
	blocking_reasons: Object.fromEntries(Object.entries(tally).sort((a, b) => b[1] - a[1])),
}, null, 1));
console.log(`species ${species.length}, moves ${moves.length}; Champions-learnable moves ${learnable.size}, modelled ${learnOk.length}; fuzz pool species ${pool.species.length}`);
